const $ = s => document.querySelector(s); let cache = null;
async function api(url, options = {}) { const r = await fetch(url, { ...options, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } }); const data = await r.json(); if (!r.ok) throw new Error(data.error || '请求失败'); return data; }
function msg(el, text, good = false) { el.textContent = text; el.className = `message ${good ? 'success' : ''}`; }
function escapeHtml(t) { const d = document.createElement('div'); d.textContent = String(t); return d.innerHTML; }
function duration(sec) { const h = Math.floor(sec / 3600), m = Math.floor(sec % 3600 / 60); return h ? `${h}小时${m}分` : `${m}分钟`; }
function date(v) { return v ? new Date(v).toLocaleString('zh-CN', { hour12: false }) : '—'; }
async function loadDashboard() { cache = await api('/api/admin/dashboard'); $('#accountRows').innerHTML = cache.accounts.length ? cache.accounts.map(a => `<tr><td><b>${escapeHtml(a.name)}</b></td><td>${duration(a.totalSeconds)}</td><td>${a.turns}</td><td>${date(a.lastPlayedAt)}</td></tr>`).join('') : '<tr><td colspan="4" class="empty">暂无游戏账号</td></tr>'; $('#modelList').innerHTML = cache.models.length ? cache.models.map(m => `<article class="model-item ${m.active ? 'active' : ''}"><div><h3>${escapeHtml(m.name)} ${m.active ? '<span>使用中</span>' : ''}</h3><p>${escapeHtml(m.model)} · ${escapeHtml(m.baseUrl)}</p></div><div>${m.active ? '' : `<button class="secondary" data-active="${m.id}">启用</button>`}<button class="danger" data-delete="${m.id}">删除</button></div></article>`).join('') : '<p class="empty">尚未配置 AI 模型，游戏剧情暂时无法生成。</p>'; }
function showPanel() { $('#adminLogin').classList.add('hidden'); $('#adminPanel').classList.remove('hidden'); }
$('#adminLoginForm').addEventListener('submit', async e => { e.preventDefault(); try { await api('/api/admin/login', { method: 'POST', body: JSON.stringify({ password: $('#adminPassword').value }) }); showPanel(); await loadDashboard(); } catch (err) { msg($('#adminLoginMessage'), err.message); } });
document.querySelectorAll('.tab').forEach(b => b.addEventListener('click', () => { document.querySelectorAll('.tab').forEach(x => x.classList.toggle('active', x === b)); document.querySelectorAll('.admin-tab').forEach(x => x.classList.add('hidden')); $(`#tab-${b.dataset.tab}`).classList.remove('hidden'); }));
$('#refreshAdmin').addEventListener('click', loadDashboard);
$('#modelForm').addEventListener('submit', async e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.target)); try { await api('/api/admin/models', { method: 'POST', body: JSON.stringify(data) }); e.target.reset(); msg($('#modelMessage'), '模型配置已添加', true); await loadDashboard(); } catch (err) { msg($('#modelMessage'), err.message); } });
$('#modelList').addEventListener('click', async e => { const active = e.target.dataset.active, del = e.target.dataset.delete; try { if (active) await api(`/api/admin/models/${active}/active`, { method: 'POST', body: '{}' }); if (del && confirm('确定删除这条模型配置？')) await api(`/api/admin/models/${del}`, { method: 'DELETE' }); await loadDashboard(); } catch (err) { msg($('#modelMessage'), err.message); } });
$('#passwordForm').addEventListener('submit', async e => { e.preventDefault(); try { await api('/api/admin/password', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(e.target))) }); e.target.reset(); msg($('#passwordMessage'), '管理密码已修改', true); } catch (err) { msg($('#passwordMessage'), err.message); } });
$('#adminLogout').addEventListener('click', async () => { await api('/api/admin/logout', { method: 'POST', body: '{}' }); location.reload(); });
loadDashboard().then(showPanel).catch(() => {});
