const $=s=>document.querySelector(s);let cache=null,editingId=null,bannerData='';
async function api(url,options={}){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}),raw=await r.text();let data;try{data=raw?JSON.parse(raw):{};}catch{throw new Error(`服务器返回 ${r.status}：${raw.slice(0,120)||'无法解析的响应'}`);}if(!r.ok)throw new Error(data.error||'请求失败');return data;}
function msg(el,text,good=false){el.textContent=text;el.className=`message ${good?'success':''}`;}function esc(t){const d=document.createElement('div');d.textContent=String(t);return d.innerHTML;}function duration(sec){const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60);return h?`${h}小时${m}分`:`${m}分钟`;}function date(v){return v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'—';}
function renderGames(){const el=$('#gameAdminList');el.innerHTML=cache.games.length?cache.games.map(g=>`<article class="admin-game ${g.paused?'paused':''}"><img src="${esc(g.banner)}" alt=""><div><h3>${esc(g.name)} ${g.paused?'<span>已暂停</span>':'<span class="online">展示中</span>'}</h3><p>${esc(g.description)}</p></div><div class="row-actions"><button class="secondary" data-edit="${g.id}">编辑</button><button class="ghost" data-pause="${g.id}">${g.paused?'恢复':'暂停'}</button><button class="danger" data-delete-game="${g.id}">删除</button></div></article>`).join(''):'<p class="empty">还没有游戏，请添加第一个游戏。</p>';}
async function loadDashboard(){cache=await api('/api/admin/dashboard');$('#accountRows').innerHTML=cache.accounts.length?cache.accounts.map(a=>`<tr><td><b>${esc(a.username)}</b></td><td>${esc(a.characterName)}</td><td>${esc(a.gameName)}</td><td>${duration(a.totalSeconds)}</td><td>${a.turns}</td><td>${date(a.lastPlayedAt)}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">暂无玩家存档</td></tr>';$('#modelList').innerHTML=cache.models.length?cache.models.map(m=>`<article class="model-item ${m.active?'active':''}"><div><h3>${esc(m.name)} ${m.active?'<span>使用中</span>':''}</h3><p>${esc(m.model)} · ${esc(m.baseUrl)}</p></div><div>${m.active?'':`<button class="secondary" data-active="${m.id}">启用</button>`}<button class="danger" data-delete="${m.id}">删除</button></div></article>`).join(''):'<p class="empty">尚未配置AI模型，游戏剧情暂时无法生成。</p>';renderGames();}
function showPanel(){$('#adminLogin').classList.add('hidden');$('#adminPanel').classList.remove('hidden');}
function selectTab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.admin-tab').forEach(x=>x.classList.add('hidden'));$(`#tab-${name}`).classList.remove('hidden');$('#gameEditor').classList.add('hidden');}
function splitOptions(value){return [...new Set(String(value||'').split(/[\n,，、;；]+/).map(x=>x.trim()).filter(Boolean))];}
function openEditor(game=null){editingId=game?.id||null;bannerData='';const f=$('#gameForm');f.reset();f.elements.id.value=editingId||'';for(const key of ['name','description','prelude','protagonist','npcs','background','rules'])f.elements[key].value=game?.[key]||'';const selected=new Set(game?.customFields||(game?['name']:['name','gender','age','occupation']));f.querySelectorAll('input[name="customFields"]').forEach(input=>input.checked=selected.has(input.value));f.elements.ageOptions.value=(game?.choiceOptions?.age||[]).join('\n');f.elements.occupationOptions.value=(game?.choiceOptions?.occupation||[]).join('\n');f.elements.allowFreeInput.checked=game?game.allowFreeInput!==false:true;$('#editorTitle').textContent=game?`编辑《${game.name}》`:'添加新游戏';$('#bannerHint').textContent=game?'不重新上传则保留现有图片':'未上传时使用默认图片';document.querySelectorAll('.admin-tab').forEach(x=>x.classList.add('hidden'));$('#gameEditor').classList.remove('hidden');}
function imageData(file){return new Promise((resolve,reject)=>{if(file.size>4*1024*1024)return reject(new Error('图片不能超过4MB'));const reader=new FileReader();reader.onerror=()=>reject(new Error('无法读取图片'));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('图片格式无效'));img.onload=()=>{const ratio=img.width/img.height;if(Math.abs(ratio-16/9)>0.04)return reject(new Error(`图片须为16:9画幅，当前约为 ${ratio.toFixed(2)}:1`));resolve(reader.result);};img.src=reader.result;};reader.readAsDataURL(file);});}
$('#adminLoginForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('#adminPassword').value})});showPanel();await loadDashboard();}catch(err){msg($('#adminLoginMessage'),err.message);}});
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>selectTab(b.dataset.tab)));$('#refreshAdmin').addEventListener('click',loadDashboard);$('#newGameBtn').addEventListener('click',()=>openEditor());$('#cancelGameEdit').addEventListener('click',()=>selectTab('games'));
$('#bannerFile').addEventListener('change',async e=>{bannerData='';if(!e.target.files[0])return;try{bannerData=await imageData(e.target.files[0]);$('#bannerHint').textContent='图片比例正确，保存时将上传';}catch(err){e.target.value='';msg($('#gameFormMessage'),err.message);}});
$('#gameForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter,form=new FormData(e.target),data=Object.fromEntries(form);data.customFields=form.getAll('customFields');data.choiceOptions={age:splitOptions(form.get('ageOptions')),occupation:splitOptions(form.get('occupationOptions'))};data.allowFreeInput=form.get('allowFreeInput')==='on';delete data.ageOptions;delete data.occupationOptions;delete data.bannerFile;button.disabled=true;msg($('#gameFormMessage'),(!data.description||!data.prelude)?'正在调用AI补充留空的文案，请稍候……':'');try{if(bannerData)data.bannerData=bannerData;await api(editingId?`/api/admin/games/${editingId}`:'/api/admin/games',{method:editingId?'PUT':'POST',body:JSON.stringify(data)});await loadDashboard();selectTab('games');}catch(err){msg($('#gameFormMessage'),err.message);}finally{button.disabled=false;}});
$('#gameAdminList').addEventListener('click',async e=>{const edit=e.target.dataset.edit,pause=e.target.dataset.pause,del=e.target.dataset.deleteGame;if(edit)return openEditor(cache.games.find(g=>g.id===edit));try{if(pause)await api(`/api/admin/games/${pause}/pause`,{method:'POST',body:'{}'});if(del&&confirm('确定永久删除这个游戏？游戏配置将被删除，已有玩家存档不会自动展示。'))await api(`/api/admin/games/${del}`,{method:'DELETE'});await loadDashboard();}catch(err){alert(err.message);}});
$('#modelForm').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{await api('/api/admin/models',{method:'POST',body:JSON.stringify(data)});e.target.reset();msg($('#modelMessage'),'模型配置已添加',true);await loadDashboard();}catch(err){msg($('#modelMessage'),err.message);}});
$('#modelList').addEventListener('click',async e=>{const active=e.target.dataset.active,del=e.target.dataset.delete;try{if(active)await api(`/api/admin/models/${active}/active`,{method:'POST',body:'{}'});if(del&&confirm('确定删除这条模型配置？'))await api(`/api/admin/models/${del}`,{method:'DELETE'});await loadDashboard();}catch(err){msg($('#modelMessage'),err.message);}});
$('#passwordForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/admin/password',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});e.target.reset();msg($('#passwordMessage'),'管理密码已修改',true);}catch(err){msg($('#passwordMessage'),err.message);}});$('#adminLogout').addEventListener('click',async()=>{await api('/api/admin/logout',{method:'POST',body:'{}'});location.reload();});loadDashboard().then(showPanel).catch(()=>{});
