const $=s=>document.querySelector(s);
const views=['homeView','detailView','loginView','setupView','gameView'];
let games=[],selectedGame=null,state=null,authResult=null,dirty=false,busy=false,typingQueue='',typingText='',typingTimer=null,typingWaiters=[];
async function api(url,options={}){const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}),raw=await response.text();let data;try{data=raw?JSON.parse(raw):{};}catch{throw new Error(`服务器返回 ${response.status}：${raw.slice(0,120)||'无法解析的响应'}`);}if(!response.ok)throw new Error(data.error||'请求失败');return data;}
function message(el,text,good=false){el.textContent=text;el.className=`message ${good?'success':''}`;}
function escapeHtml(text){const div=document.createElement('div');div.textContent=String(text);return div.innerHTML;}
function escapeAttr(text){return String(text??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function show(name){views.forEach(id=>$(`#${id}`).classList.toggle('hidden',id!==name));$('#siteHero').classList.toggle('hidden',name!=='homeView');window.scrollTo({top:0,behavior:'smooth'});}
function gameCard(game){return `<article class="game-card card" data-game="${game.id}" tabindex="0"><img src="${escapeHtml(game.banner)}" alt="${escapeHtml(game.name)}题头"><div><span class="eyebrow">PLAYABLE MUD</span><h2>${escapeHtml(game.name)}</h2><p>${escapeHtml(game.description)}</p><button class="primary">进入游戏</button></div></article>`;}
async function loadGames(){try{const data=await api('/api/games');games=data.games;$('#gameList').innerHTML=games.length?games.map(gameCard).join(''):'<div class="card empty-state"><h2>游戏正在筹备中</h2><p>管理员还没有发布可玩的MUD游戏。</p></div>';}catch(err){message($('#homeMessage'),err.message);}}
function openDetail(id){selectedGame=games.find(x=>x.id===id);if(!selectedGame)return;$('#detailBanner').src=selectedGame.banner;$('#detailName').textContent=selectedGame.name;$('#detailDescription').textContent=selectedGame.description;history.replaceState(null,'',`/?game=${encodeURIComponent(id)}`);show('detailView');}
function beginLogin(){if(!selectedGame)return;$('#loginTitle').textContent=`进入《${selectedGame.name}》`;$('#loginBanner').src=selectedGame.banner;show('loginView');}
function goHome(){selectedGame=null;state=null;history.replaceState(null,'','/');show('homeView');loadGames();}
function characterField(field,value=''){const v=escapeAttr(value);if(field==='name')return `<label>主角姓名<input name="character.name" maxlength="20" value="${v}" placeholder="输入主角姓名"></label>`;if(field==='gender')return `<label>性别<input name="character.gender" maxlength="20" value="${v}" placeholder="如：男、女"></label>`;if(field==='age')return `<label>年龄<input name="character.age" type="number" min="1" max="120" value="${v}" placeholder="输入年龄"></label>`;if(field==='occupation')return `<label>职业<input name="character.occupation" maxlength="40" value="${v}" placeholder="输入职业或身份"></label>`;return '';}
function syncSetupMode(){const continuing=$('#continueMode').checked;$('#characterFields').classList.toggle('fields-disabled',continuing);$('#characterFields').querySelectorAll('input').forEach(input=>input.disabled=continuing);$('#setupHint').textContent=continuing?'将载入该游戏已有进度，主角资料沿用存档。':'请设置本游戏允许玩家自定义的主角元素；未显示的部分按默认设定或由AI合理生成。';}
function openSetup(data){authResult=data;selectedGame=data.game;$('#setupBanner').src=data.game.banner;$('#setupTitle').textContent=`设置《${data.game.name}》的主角`;const fields=data.game.customFields||[];$('#characterFields').innerHTML=fields.length?fields.map(field=>characterField(field,data.character?.[field])).join(''):'<p class="muted no-custom-fields">本游戏没有需要玩家填写的主角元素，将采用默认设定或由AI合理生成。</p>';$('#continueMode').disabled=!data.hasSave;$('#continueMode').checked=data.hasSave;$('#restartMode').checked=!data.hasSave;syncSetupMode();show('setupView');}
function renderMeta(next){state=next;$('#chapter').textContent=next.chapter||'';$('#location').textContent=next.location||'未知地点';$('#time').textContent=next.time||'';$('#statName').textContent=next.playerName;$('#statTurn').textContent=`第 ${next.turn} 回合`;$('#statHp').textContent=next.hpStatus||'—';const resources=Object.entries(next.resources||{});$('#resources').innerHTML=resources.length?resources.map(([k,v])=>`<div class="resource"><span>${escapeHtml(resourceName(k))}</span><b>${escapeHtml(v)}</b></div>`).join(''):'<p class="muted">暂无特殊资源</p>';$('#inventory').innerHTML=(next.inventory||[]).length?`<p>${next.inventory.map(escapeHtml).join(' · ')}</p>`:'';const rel=Object.entries(next.relations||{});$('#relations').innerHTML=rel.length?rel.map(([name,value])=>`<div class="affection"><div><span>${escapeHtml(name)}</span><b>${value}</b></div><i><em style="width:${Math.max(0,Math.min(100,(Number(value)+100)/2))}%"></em></i></div>`).join(''):'<p class="muted">尚无记录</p>';}
function resourceName(k){return ({antibiotic:'抗生素（片）',flashlight:'强光手电（次）',lighter:'防风打火机'})[k]||k;}
function renderStory(text){$('#storyText').classList.remove('streaming');$('#storyText').innerHTML=String(text||'').split(/\n+/).filter(Boolean).map(p=>`<p>${escapeHtml(p)}</p>`).join('');}
function renderOptions(options=[]){$('#options').innerHTML=options.map((o,i)=>`<button data-option="${i+1}"><span>${i+1}</span>${escapeHtml(o)}</button>`).join('');}
function render(next){renderMeta(next);renderStory(next.narrative);renderOptions(next.options);}
function setBusy(v){busy=v;$('#busy').classList.toggle('hidden',!v);['sendBtn','actionInput','saveBtn','quitBtn'].forEach(id=>$(`#${id}`).disabled=v);}
function hideBusy(){ $('#busy').classList.add('hidden'); }
function resetTyping(){if(typingTimer)clearTimeout(typingTimer);typingTimer=null;typingQueue='';typingText='';typingWaiters.splice(0).forEach(r=>r());$('#storyText').textContent='';$('#storyText').classList.add('streaming');}
function runTyping(){if(typingTimer||!typingQueue)return;const tick=()=>{if(!typingQueue){typingTimer=null;typingWaiters.splice(0).forEach(r=>r());return;}typingText+=typingQueue[0];typingQueue=typingQueue.slice(1);$('#storyText').textContent=typingText;typingTimer=setTimeout(tick,typingQueue.length>160?6:typingQueue.length>60?10:16);};typingTimer=setTimeout(tick,0);}
function enqueueNarrative(t){typingQueue+=t;runTyping();}function waitForTyping(){return !typingQueue&&!typingTimer?Promise.resolve():new Promise(r=>typingWaiters.push(r));}
async function readTurnStream(response){if(!response.ok){const raw=await response.text();try{throw new Error(JSON.parse(raw).error||'请求失败');}catch(e){if(e instanceof SyntaxError)throw new Error(`服务器返回 ${response.status}：${raw.slice(0,120)}`);throw e;}}if(!response.body)throw new Error('浏览器无法接收流式剧情');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',completed=null;const handle=e=>{if(e.type==='narrative'){hideBusy();enqueueNarrative(e.text||'');}if(e.type==='complete')completed=e;if(e.type==='error')throw new Error(e.error||'剧情生成失败');};while(true){const{value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split(/\r?\n/);buffer=lines.pop()||'';for(const line of lines)if(line.trim())handle(JSON.parse(line));}if(buffer.trim())handle(JSON.parse(buffer));if(!completed)throw new Error('剧情流意外中断，请重试');return completed;}
async function takeTurn(input){if(busy)return;const previous=state;setBusy(true);message($('#gameMessage'),'');$('#options').innerHTML='';$('#actionInput').value='';resetTyping();try{const response=await fetch('/api/game/turn',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({input})}),completed=await readTurnStream(response);await waitForTyping();dirty=true;renderStory(completed.state.narrative);renderMeta(completed.state);renderOptions(completed.state.options);message($('#gameMessage'),'剧情与状态已更新',true);}catch(err){if(previous)render(previous);message($('#gameMessage'),err.message);}finally{setBusy(false);}}
function applyReading(size,bold){const story=$('#storyText');story.classList.remove('text-small','text-medium','text-large');story.classList.add(`text-${size}`);story.classList.toggle('text-bold',bold);document.querySelectorAll('[data-size]').forEach(b=>b.classList.toggle('active',b.dataset.size===size));$('#boldToggle').checked=bold;localStorage.setItem('mud-reading',JSON.stringify({size,bold}));}
function loadReading(){try{const x=JSON.parse(localStorage.getItem('mud-reading'));applyReading(['small','medium','large'].includes(x?.size)?x.size:'medium',Boolean(x?.bold));}catch{applyReading('medium',false);}}
async function quit(save){try{await api('/api/game/quit',{method:'POST',body:JSON.stringify({save})});dirty=false;if($('#quitDialog').open)$('#quitDialog').close();location.assign('/');}catch(err){message($('#gameMessage'),err.message);}}

$('#gameList').addEventListener('click',e=>{const card=e.target.closest('[data-game]');if(card)openDetail(card.dataset.game);});
$('#gameList').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-game]'))openDetail(e.target.dataset.game);});
$('#detailBack').addEventListener('click',goHome);$('#backHomeBtn').addEventListener('click',goHome);$('#startGameBtn').addEventListener('click',beginLogin);$('#loginBack').addEventListener('click',()=>show('detailView'));
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const submit=e.submitter;submit.disabled=true;try{const data=await api('/api/game/auth',{method:'POST',body:JSON.stringify({gameId:selectedGame.id,username:$('#username').value,password:$('#playerPassword').value,legacyName:$('#legacyName').value})});message($('#loginMessage'),'');openSetup(data);}catch(err){message($('#loginMessage'),err.message);}finally{submit.disabled=false;}});
$('#continueMode').addEventListener('change',syncSetupMode);$('#restartMode').addEventListener('change',syncSetupMode);$('#setupBack').addEventListener('click',()=>show('loginView'));
$('#setupForm').addEventListener('submit',async e=>{e.preventDefault();const submit=e.submitter,form=new FormData(e.target),character={};for(const field of selectedGame.customFields||[]){const value=form.get(`character.${field}`);if(value!==null)character[field]=value;}submit.disabled=true;try{const data=await api('/api/game/start',{method:'POST',body:JSON.stringify({mode:form.get('mode'),character})});dirty=false;$('#gameBanner').src=selectedGame.banner;show('gameView');render(data.state);loadReading();}catch(err){message($('#setupMessage'),err.message);}finally{submit.disabled=false;}});
$('#options').addEventListener('click',e=>{const b=e.target.closest('button[data-option]');if(b&&!busy)takeTurn(`${b.dataset.option}. ${b.textContent.slice(1).trim()}`);});$('#actionForm').addEventListener('submit',e=>{e.preventDefault();const v=$('#actionInput').value.trim();if(v)takeTurn(v);});
$('#saveBtn').addEventListener('click',async()=>{try{await api('/api/game/save',{method:'POST',body:'{}'});dirty=false;message($('#gameMessage'),'进度已保存',true);}catch(err){message($('#gameMessage'),err.message);}});$('#quitBtn').addEventListener('click',()=>{if(dirty)$('#quitDialog').showModal();else quit(false);});$('#saveQuit').addEventListener('click',e=>{e.preventDefault();quit(true);});$('#discardQuit').addEventListener('click',e=>{e.preventDefault();quit(false);});
document.querySelectorAll('[data-size]').forEach(b=>b.addEventListener('click',()=>applyReading(b.dataset.size,$('#boldToggle').checked)));$('#boldToggle').addEventListener('change',e=>applyReading(document.querySelector('[data-size].active')?.dataset.size||'medium',e.target.checked));
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});setInterval(()=>{if(state&&!document.hidden)fetch('/api/game/heartbeat',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).catch(()=>{});},30000);
await loadGames();const requested=new URLSearchParams(location.search).get('game');if(requested)openDetail(requested);api('/api/game/state').then(data=>{selectedGame=data.state.game;$('#gameBanner').src=selectedGame.banner;show('gameView');dirty=data.dirty;render(data.state);loadReading();}).catch(()=>{});
