import http from 'node:http';
import { readFile, writeFile, mkdir, rename } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = path.resolve(process.env.DATA_DIR || path.join(ROOT, 'data'));
const BANNER_DIR = path.join(DATA_DIR, 'banners');
const PORT = Number(process.env.PORT || 3000);
const APP_SECRET = process.env.APP_SECRET || 'development-only-change-this-secret';
const SESSION_TTL = 12 * 60 * 60 * 1000;
const PLAYER_TTL = 24 * 60 * 60 * 1000;
const MAX_BODY = 8 * 1024 * 1024;
const DEFAULT_GAME_ID = 'ponan-longshe';
const DEFAULT_BANNER = '/gomudbanner.png';
const CUSTOM_FIELDS = ['name','gender','age','occupation','personality'];
const playerSessions = new Map();
const adminSessions = new Map();
const mime = { '.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml; charset=utf-8' };

await mkdir(BANNER_DIR, { recursive: true });
const legacyConfig = JSON.parse(await readFile(path.join(ROOT, 'game-settings.json'), 'utf8'));
await ensureStore('accounts.json', { accounts: [] });
await ensureStore('admin.json', { passwordHash: hashPassword(process.env.ADMIN_PASSWORD || 'pnls-admin-2026') });
await ensureStore('models.json', initialModels());
await ensureStore('games.json', { games: [defaultGame()] });

function defaultGame() {
  return {
    id: DEFAULT_GAME_ID, name: '坡南龙蛇', banner: '/pnlsbanner.png', paused: false,
    description: '南宋绍兴年间，温州大学学生尚风在平阳县北门河心亭意外醒来，发现自己已穿越千年。背包中的抗生素、强光手电和防风打火机成了保命底牌。此时金国暗线与海贼势力正借“疾草帮”渗透地方，一场从码头异动开始的追查，将把他卷入江湖、官府与家国危局。',
    protagonist: '尚风，温州大学大四男生，爱好动漫和电子游戏，具备现代大学生常识。',
    customFields: ['name'],
    npcs: legacyConfig.heroines.map(x => `${x.name}：${x.profile}（最早第${x.earliestTurn}回合登场）`).join('\n'),
    background: `${legacyConfig.world.era}。${legacyConfig.world.conflict}\n主要活动范围：${legacyConfig.world.mainArea}。\n主线：${legacyConfig.world.mainQuest}`,
    rules: legacyConfig.rules.join('\n'), engine: legacyConfig, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString()
  };
}
function initialModels() {
  const models = [];
  if (process.env.AI_API_KEY && process.env.AI_BASE_URL && process.env.AI_MODEL) models.push({ id:crypto.randomUUID(),name:process.env.AI_NAME||'默认模型',baseUrl:process.env.AI_BASE_URL,model:process.env.AI_MODEL,apiKey:encrypt(process.env.AI_API_KEY),active:true,createdAt:new Date().toISOString() });
  return { models };
}
async function ensureStore(name, data) { const file=path.join(DATA_DIR,name); if(!existsSync(file)) await atomicWrite(file,data); }
async function load(name) { return JSON.parse(await readFile(path.join(DATA_DIR,name),'utf8')); }
async function save(name,data) { return atomicWrite(path.join(DATA_DIR,name),data); }
async function atomicWrite(file,data) { const tmp=`${file}.${crypto.randomUUID()}.tmp`; await writeFile(tmp,JSON.stringify(data,null,2),{mode:0o600}); await rename(tmp,file); }
function hashPassword(value,salt=crypto.randomBytes(16).toString('hex')) { return `${salt}:${crypto.scryptSync(String(value),salt,64).toString('hex')}`; }
function verifyPassword(value,stored='') { const [salt,expected]=stored.split(':'); if(!salt||!expected)return false; const actual=crypto.scryptSync(String(value),salt,64); const target=Buffer.from(expected,'hex'); return actual.length===target.length&&crypto.timingSafeEqual(actual,target); }
function cipherKey(){return crypto.createHash('sha256').update(APP_SECRET).digest();}
function encrypt(value){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',cipherKey(),iv),data=Buffer.concat([c.update(value,'utf8'),c.final()]);return [iv.toString('hex'),c.getAuthTag().toString('hex'),data.toString('hex')].join('.');}
function decrypt(value){const [iv,tag,data]=String(value).split('.'),d=crypto.createDecipheriv('aes-256-gcm',cipherKey(),Buffer.from(iv,'hex'));d.setAuthTag(Buffer.from(tag,'hex'));return Buffer.concat([d.update(Buffer.from(data,'hex')),d.final()]).toString('utf8');}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>x.trim().split(/=(.*)/s).slice(0,2).map(decodeURIComponent)));}
function setCookie(res,name,value,maxAge=43200){res.setHeader('Set-Cookie',`${name}=${encodeURIComponent(value)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${maxAge}${process.env.NODE_ENV==='production'?'; Secure':''}`);}
function clearCookie(res,name){res.setHeader('Set-Cookie',`${name}=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0`);}
function send(res,status,payload){const b=JSON.stringify(payload);res.writeHead(status,{'Content-Type':mime['.json'],'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(b);}
function fail(res,status,message){send(res,status,{ok:false,error:message});}
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(Buffer.byteLength(raw)>MAX_BODY)throw Object.assign(new Error('请求内容过大'),{public:true});}return raw?JSON.parse(raw):{};}
function safePlayer(req){const token=cookies(req).mud_session,s=playerSessions.get(token);if(!s||Date.now()-s.lastSeen>PLAYER_TTL){if(token)playerSessions.delete(token);return null;}s.lastSeen=Date.now();return s;}
function safeAdmin(req){const token=cookies(req).mud_admin,s=adminSessions.get(token);if(!s||Date.now()-s.lastSeen>SESSION_TTL){if(token)adminSessions.delete(token);return null;}s.lastSeen=Date.now();return s;}
function clamp(n,min,max){return Math.max(min,Math.min(max,Number(n)));}
function bannerOf(g){return !g.banner||g.banner==='/default-banner.svg'?DEFAULT_BANNER:g.banner;}
function introOf(g){let text=String(g.description||'').replace(/\s+/g,'').trim();if(Array.from(text).length<100)text+=`。${String(g.background||'').replace(/\s+/g,'').trim()}。故事开始前，主角已经来到命运转折的入口，接下来的身份、线索与危险，都将由玩家亲自探索并作出选择。世界表面仍维持着日常秩序，但暗处的矛盾已经汇聚，主角最初看到的异常将成为进入主线的第一把钥匙。`;return Array.from(text).slice(0,300).join('');}
function parseChoices(value,max=20){const source=Array.isArray(value)?value:String(value||'').split(/[\n,，、;；]+/);return [...new Set(source.map(x=>String(x).trim().slice(0,30)).filter(Boolean))].slice(0,max);}
function choiceOptionsOf(g){const raw=g.choiceOptions&&typeof g.choiceOptions==='object'?g.choiceOptions:{},age=parseChoices(raw.age),occupation=parseChoices(raw.occupation),personality=parseChoices(raw.personality);return {gender:['男','女','随机'],age:age.length?age:['18','20','22','25','30','35','40','随机'],occupation:occupation.length?occupation:['沿用默认设定','随机生成'],personality:personality.length?personality:['沉稳','勇敢','机敏','善良','谨慎','随机']};}
function gamePublic(g){return {id:g.id,name:g.name,banner:bannerOf(g),description:introOf(g),customFields:Array.isArray(g.customFields)?g.customFields:['name'],choiceOptions:choiceOptionsOf(g),paused:Boolean(g.paused)};}
async function findGame(id,{includePaused=false}={}){const db=await load('games.json');const game=db.games.find(x=>x.id===id);return game&&(!game.paused||includePaused)?game:null;}

function defaultRules(){return [
  '除非游戏设定明确要求上帝视角，否则必须采用高自由度的主角有限视角叙事，玩家既可选择固定选项，也可自由输入合理行动。',
  '除必要的背景介绍、情节铺垫和场景过渡外，只能叙述主角当下能够看见、听见、触碰、回忆、推断或通过合理渠道获知的信息。',
  '陌生人物的姓名、身份、动机、经历、关系和隐秘行动不能自动告知玩家，必须由主角观察、交谈、询问、调查或从可信线索中逐步获得；未获知前使用外貌、衣着、声音等可感知特征称呼。',
  '主角在前20个回合享有新手豁免：不会死亡，也不会遭受无法挽回的永久失败；危险应转化为受伤、失误、被俘或合理脱身。',
  '每回合必须提供四个互不重复、可执行且能推动剧情的选项。',
  '场景、社会身份、交通、通信、伤病、物品消耗和人物行为必须符合时代背景、世界设定、基本生活逻辑与自然规律。',
  '鬼怪、魔幻、奇幻武侠等题材可在明确设定范围内虚构或夸张，但设定以外不得随意破坏因果与世界规则。',
  '不得替玩家擅自决定关键行动；叙述停在需要玩家决定的时刻。'
];}
function initialResources(game){if(game.engine?.items)return {antibiotic:30,flashlight:30,lighter:999};return {};}
function initialInventory(game){return game.engine?.items?.daily?[...game.engine.items.daily]:[];}
function newGame(username,character,game){const opening=game.engine?.opening,playerName=character.name||(game.id===DEFAULT_GAME_ID?'尚风':'主角');return {gameId:game.id,username,character,playerName,turn:0,chapter:opening?.chapter||'序章',location:opening?.location||'故事起点',time:opening?.time||'故事开始',hpStatus:'状态良好',resources:initialResources(game),inventory:initialInventory(game),relations:{},flags:{},narrative:opening?.intro||`你即将进入《${game.name}》的世界。故事尚未落笔，先观察周围环境，再决定第一步行动。`,options:opening?.options||['观察周围环境','检查自身与随身物品','寻找可以交谈的人','谨慎向前探索'],longTermSummary:`${playerName}进入《${game.name}》，故事刚刚开始。`,history:[],updatedAt:new Date().toISOString()};}
function normalizeState(state,game){const next=structuredClone(state||{});next.gameId=game.id;next.history=Array.isArray(next.history)?next.history:[];next.resources=next.resources&&typeof next.resources==='object'?next.resources:{};next.inventory=Array.isArray(next.inventory)?next.inventory:[];next.relations=next.relations&&typeof next.relations==='object'?next.relations:(next.affections||{});next.flags=next.flags&&typeof next.flags==='object'?next.flags:{};next.character=next.character&&typeof next.character==='object'?next.character:{name:next.playerName||''};if(game.engine?.heroines){if(!Array.isArray(next.introducedHeroines)){const known=[next.narrative,...next.history.map(x=>x.narrative)].filter(Boolean).join('\n');next.introducedHeroines=game.engine.heroines.filter(h=>Number(next.relations[h.name]||0)!==0||known.includes(h.name)).map(h=>h.name);}next.introducedHeroines=[...new Set(next.introducedHeroines)].filter(name=>game.engine.heroines.some(h=>h.name===name));}next.longTermSummary=String(next.longTermSummary||next.summary||`${next.playerName||'主角'}的故事刚刚开始。`).slice(0,2400);return next;}
function publicState(state,game){const next=normalizeState(state,game);let relations=next.relations;if(game.engine?.heroines){const visible=new Set(next.introducedHeroines||[]);relations=Object.fromEntries(Object.entries(relations).filter(([name])=>visible.has(name)));}return {...next,relations,affections:undefined,history:next.history.slice(-5),longTermSummary:undefined,summary:undefined,game:gamePublic(game)};}
function mergePatch(state,patch={}){const next=structuredClone(state);for(const k of ['chapter','location','time','hpStatus'])if(typeof patch[k]==='string')next[k]=patch[k].slice(0,160);if(patch.resources&&typeof patch.resources==='object')for(const [k,v] of Object.entries(patch.resources)){if(typeof v==='number'||typeof v==='string')next.resources[String(k).slice(0,60)]=typeof v==='number'?clamp(v,0,999999):String(v).slice(0,80);}if(patch.relations&&typeof patch.relations==='object')for(const [k,v] of Object.entries(patch.relations))next.relations[String(k).slice(0,60)]=clamp(v,-100,100);if(patch.affections&&typeof patch.affections==='object')for(const [k,v] of Object.entries(patch.affections))next.relations[String(k).slice(0,60)]=clamp(v,-100,100);if(Array.isArray(patch.inventory))next.inventory=patch.inventory.filter(x=>typeof x==='string').slice(0,50);if(Array.isArray(patch.introducedHeroines))next.introducedHeroines=[...new Set([...(next.introducedHeroines||[]),...patch.introducedHeroines])];if(patch.flags&&typeof patch.flags==='object')next.flags={...next.flags,...patch.flags};return next;}
function migrateAccount(account){account.games=account.games&&typeof account.games==='object'?account.games:{};if(account.game&&!account.games[DEFAULT_GAME_ID])account.games[DEFAULT_GAME_ID]={state:account.game,totalSeconds:account.totalSeconds||0};return account;}
function accountRows(accounts,games){const names=Object.fromEntries(games.map(g=>[g.id,g.name]));return accounts.flatMap(a=>{migrateAccount(a);return Object.entries(a.games).map(([gameId,entry])=>({id:a.id,username:a.username||a.name||'旧版账号',characterName:entry.state?.character?.name||entry.state?.playerName||'—',gameId,gameName:names[gameId]||'已删除游戏',totalSeconds:entry.totalSeconds||0,turns:entry.state?.turn||0,lastPlayedAt:entry.lastPlayedAt||a.lastPlayedAt,createdAt:a.createdAt}));});}

function cleanGameInput(data,existing=null){const req=(key,max,optional=false)=>{const v=String(data[key]??existing?.[key]??'').trim().slice(0,max);if(!optional&&!v)throw Object.assign(new Error(`请填写${({name:'游戏名称',description:'游戏简介',protagonist:'主角设定',background:'游戏背景',rules:'核心规则和机制'})[key]}`),{public:true});return v;};const rawDescription=String(data.description??existing?.description??'').trim(),introLength=Array.from(rawDescription.replace(/\s/g,'')).length;if(introLength<100||introLength>300)throw Object.assign(new Error('游戏简介须为100至300字，包含游戏背景和前置情节'),{public:true});const description=Array.from(rawDescription).slice(0,300).join(''),customFields=Array.isArray(data.customFields)?data.customFields.filter(x=>CUSTOM_FIELDS.includes(x)):(Array.isArray(existing?.customFields)?existing.customFields:['name']);const incoming=data.choiceOptions&&typeof data.choiceOptions==='object'?data.choiceOptions:null,previous=existing?.choiceOptions||{};const choiceOptions={age:parseChoices(incoming?incoming.age:previous.age),occupation:parseChoices(incoming?incoming.occupation:previous.occupation),personality:parseChoices(incoming?incoming.personality:previous.personality)};return {name:req('name',60),description,protagonist:req('protagonist',3000),npcs:req('npcs',5000,true),background:req('background',8000),rules:req('rules',8000),customFields:[...new Set(customFields)],choiceOptions};}
function sanitizeCharacter(raw,game){const allowed=Array.isArray(game.customFields)?game.customFields:['name'],choices=choiceOptionsOf(game),out={},invalid=(label)=>Object.assign(new Error(`请选择有效的主角${label}`),{public:true});for(const field of allowed){if(field==='name'){const value=String(raw?.name||'').trim().slice(0,20);if(!/^[\p{L}\p{N}_·\-]{1,20}$/u.test(value))throw Object.assign(new Error('主角姓名须为1至20个汉字、字母或数字'),{public:true});out.name=value;}if(field==='gender'){const value=String(raw?.gender||'');if(!choices.gender.includes(value))throw invalid('性别');out.gender=value;}if(field==='age'){const value=String(raw?.age||'');if(!choices.age.includes(value))throw invalid('年龄');out.age=/^\d+$/.test(value)?Number(value):value;}if(field==='occupation'){const value=String(raw?.occupation||'');if(!choices.occupation.includes(value))throw invalid('职业');out.occupation=value;}if(field==='personality'){let value=Array.isArray(raw?.personality)?raw.personality.map(String):[];value=[...new Set(value)];if(!value.length||value.length>5||value.some(x=>!choices.personality.includes(x)))throw invalid('性格');if(value.includes('随机'))value=['随机'];out.personality=value;}}return out;}
async function saveBanner(dataUrl,gameId){if(!dataUrl)return null;const match=/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/=]+)$/.exec(dataUrl);if(!match)throw Object.assign(new Error('题头图片仅支持 PNG、JPG 或 WebP'),{public:true});const bytes=Buffer.from(match[2],'base64');if(bytes.length>4*1024*1024)throw Object.assign(new Error('题头图片不能超过4MB'),{public:true});const ext=match[1]==='jpeg'?'jpg':match[1],name=`${gameId}-${Date.now()}.${ext}`;await writeFile(path.join(BANNER_DIR,name),bytes,{mode:0o600});return `/uploads/${name}`;}

async function routeApi(req,res,url){
  if(req.method==='GET'&&url.pathname==='/api/health'){const [md,gd]=await Promise.all([load('models.json'),load('games.json')]);return send(res,200,{ok:true,modelConfigured:md.models.some(x=>x.active),activeGames:gd.games.filter(x=>!x.paused).length});}
  if(req.method==='GET'&&url.pathname==='/api/games'){const gd=await load('games.json');return send(res,200,{ok:true,games:gd.games.filter(x=>!x.paused).map(gamePublic)});}
  const publicGameMatch=url.pathname.match(/^\/api\/games\/([^/]+)$/);if(req.method==='GET'&&publicGameMatch){const game=await findGame(publicGameMatch[1]);if(!game)return fail(res,404,'游戏不存在或已暂停');return send(res,200,{ok:true,game:gamePublic(game)});}

  if(req.method==='POST'&&url.pathname==='/api/game/auth'){
    const data=await body(req),game=await findGame(String(data.gameId||''));if(!game)return fail(res,404,'游戏不存在或已暂停');const username=String(data.username||'').trim(),password=String(data.password||''),legacyName=String(data.legacyName||'').trim();
    if(!/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6}$/.test(username))return fail(res,400,'用户名须为6位英文和数字组合，且同时包含字母和数字');if(!/^\d{6}$/.test(password))return fail(res,400,'密码必须是6位数字');
    const db=await load('accounts.json');let account=db.accounts.find(x=>x.usernameKey===username.toLowerCase());
    if(!account&&legacyName){account=db.accounts.find(x=>!x.usernameKey&&x.nameKey===legacyName.toLocaleLowerCase('zh-CN'));if(!account||!verifyPassword(password,account.passwordHash))return fail(res,401,'旧版主角姓名或密码不正确');account.username=username;account.usernameKey=username.toLowerCase();}
    if(account&&!verifyPassword(password,account.passwordHash))return fail(res,401,'用户名或密码不正确');if(!account){account={id:crypto.randomUUID(),username,usernameKey:username.toLowerCase(),passwordHash:hashPassword(password),games:{},createdAt:new Date().toISOString()};db.accounts.push(account);}migrateAccount(account);await save('accounts.json',db);
    const entry=account.games[game.id],token=crypto.randomBytes(32).toString('hex');playerSessions.set(token,{accountId:account.id,gameId:game.id,stage:'setup',draft:null,dirty:false,lastSeen:Date.now(),activeSeconds:0});setCookie(res,'mud_session',token,86400);return send(res,200,{ok:true,hasSave:Boolean(entry?.state),character:entry?.state?.character||{name:entry?.state?.playerName||''},game:gamePublic(game)});
  }
  if(req.method==='POST'&&url.pathname==='/api/game/start'){
    const s=safePlayer(req);if(!s||s.stage!=='setup')return fail(res,401,'请先验证用户名和密码');const game=await findGame(s.gameId);if(!game)return fail(res,404,'游戏不存在或已暂停');const data=await body(req),mode=String(data.mode||'');if(!['continue','restart'].includes(mode))return fail(res,400,'请选择继续游戏或重新开始');
    const db=await load('accounts.json'),account=db.accounts.find(x=>x.id===s.accountId);if(!account)return fail(res,404,'账号不存在');migrateAccount(account);let entry=account.games[game.id];if(mode==='continue'&&!entry?.state)return fail(res,404,'此账号在该游戏中还没有存档，请选择“重新开始”');if(mode==='restart'){const character=sanitizeCharacter(data.character||{},game);entry=account.games[game.id]={state:newGame(account.username,character,game),totalSeconds:entry?.totalSeconds||0,lastPlayedAt:new Date().toISOString()};await save('accounts.json',db);}s.draft=normalizeState(entry.state,game);s.stage='game';s.dirty=false;return send(res,200,{ok:true,state:publicState(s.draft,game)});
  }
  if(req.method==='GET'&&url.pathname==='/api/game/state'){const s=safePlayer(req);if(!s||s.stage!=='game'||!s.draft)return fail(res,401,'请先进入游戏');const game=await findGame(s.gameId,{includePaused:true});if(!game)return fail(res,404,'游戏已不存在');return send(res,200,{ok:true,state:publicState(s.draft,game),dirty:s.dirty});}
  if(req.method==='POST'&&url.pathname==='/api/game/heartbeat'){const s=safePlayer(req);if(!s)return fail(res,401,'登录已失效');s.activeSeconds+=30;return send(res,200,{ok:true});}
  if(req.method==='POST'&&url.pathname==='/api/game/turn'){
    const s=safePlayer(req);if(!s)return fail(res,401,'请先进入游戏');const game=await findGame(s.gameId);if(!game)return fail(res,409,'游戏已暂停，请保存并返回首页');const data=await body(req),input=String(data.input||'').trim().slice(0,500);if(!input)return fail(res,400,'请输入行动');
    res.writeHead(200,{'Content-Type':'application/x-ndjson; charset=utf-8','Cache-Control':'no-cache, no-transform','X-Accel-Buffering':'no','X-Content-Type-Options':'nosniff'});const emit=p=>res.write(`${JSON.stringify(p)}\n`);
    try{emit({type:'start'});const result=await runAiTurn(s.draft,input,game,text=>emit({type:'narrative',text}));let next=mergePatch(s.draft,result.patch);next.turn+=1;next.narrative=result.narrative;next.options=result.options;next.longTermSummary=result.longTermSummary||next.longTermSummary;next.updatedAt=new Date().toISOString();if(game.engine?.heroines){const introduced=new Set(next.introducedHeroines||[]);for(const h of game.engine.heroines)if(next.turn>=h.earliestTurn&&result.narrative.includes(h.name))introduced.add(h.name);next.introducedHeroines=[...introduced];}next.history=[...(next.history||[]),{turn:next.turn,input,narrative:result.narrative,options:result.options}].slice(-60);s.draft=next;s.dirty=true;emit({type:'complete',state:publicState(next,game),dirty:true});res.end();}catch(err){console.error(err);emit({type:'error',error:err.public?err.message:'服务器暂时出了问题，请稍后再试'});res.end();}return;
  }
  if(req.method==='POST'&&url.pathname==='/api/game/save'){const s=safePlayer(req);if(!s)return fail(res,401,'请先进入游戏');await persistSession(s);s.dirty=false;return send(res,200,{ok:true,message:'进度已保存'});}
  if(req.method==='POST'&&url.pathname==='/api/game/quit'){const s=safePlayer(req);if(!s)return fail(res,401,'请先进入游戏');const data=await body(req);if(data.save)await persistSession(s);playerSessions.delete(cookies(req).mud_session);clearCookie(res,'mud_session');return send(res,200,{ok:true});}

  if(req.method==='POST'&&url.pathname==='/api/admin/login'){const data=await body(req),admin=await load('admin.json');if(!verifyPassword(String(data.password||''),admin.passwordHash))return fail(res,401,'管理密码错误');const token=crypto.randomBytes(32).toString('hex');adminSessions.set(token,{lastSeen:Date.now()});setCookie(res,'mud_admin',token);return send(res,200,{ok:true});}
  if(url.pathname.startsWith('/api/admin/')&&!safeAdmin(req))return fail(res,401,'管理员登录已失效');
  if(req.method==='GET'&&url.pathname==='/api/admin/dashboard'){const [db,md,gd]=await Promise.all([load('accounts.json'),load('models.json'),load('games.json')]);return send(res,200,{ok:true,accounts:accountRows(db.accounts,gd.games),models:md.models.map(x=>({...x,apiKey:undefined,hasKey:true})),games:gd.games.map(x=>({...x,banner:bannerOf(x),description:introOf(x),customFields:Array.isArray(x.customFields)?x.customFields:['name'],choiceOptions:choiceOptionsOf(x),engine:undefined}))});}
  if(req.method==='POST'&&url.pathname==='/api/admin/password'){const data=await body(req),admin=await load('admin.json');if(!verifyPassword(String(data.currentPassword||''),admin.passwordHash))return fail(res,400,'原密码不正确');if(String(data.newPassword||'').length<8)return fail(res,400,'新密码至少8位');admin.passwordHash=hashPassword(data.newPassword);await save('admin.json',admin);return send(res,200,{ok:true});}
  if(req.method==='POST'&&url.pathname==='/api/admin/models'){const data=await body(req);if(![data.name,data.baseUrl,data.model,data.apiKey].every(x=>String(x||'').trim()))return fail(res,400,'请填写完整模型信息');let parsed;try{parsed=new URL(data.baseUrl);}catch{return fail(res,400,'接口地址无效');}if(parsed.protocol!=='https:'&&!(process.env.NODE_ENV!=='production'&&parsed.protocol==='http:'))return fail(res,400,'生产环境接口必须使用 HTTPS');const md=await load('models.json'),item={id:crypto.randomUUID(),name:String(data.name).slice(0,40),baseUrl:parsed.toString().replace(/\/$/,''),model:String(data.model).slice(0,100),apiKey:encrypt(String(data.apiKey)),active:md.models.length===0,createdAt:new Date().toISOString()};md.models.push(item);await save('models.json',md);return send(res,200,{ok:true});}
  const activeMatch=url.pathname.match(/^\/api\/admin\/models\/([^/]+)\/active$/);if(req.method==='POST'&&activeMatch){const md=await load('models.json');if(!md.models.some(x=>x.id===activeMatch[1]))return fail(res,404,'模型不存在');md.models.forEach(x=>x.active=x.id===activeMatch[1]);await save('models.json',md);return send(res,200,{ok:true});}
  const modelDelete=url.pathname.match(/^\/api\/admin\/models\/([^/]+)$/);if(req.method==='DELETE'&&modelDelete){const md=await load('models.json');md.models=md.models.filter(x=>x.id!==modelDelete[1]);await save('models.json',md);return send(res,200,{ok:true});}
  if(req.method==='POST'&&url.pathname==='/api/admin/games'){
    const data=await body(req),fields=cleanGameInput(data),id=crypto.randomUUID(),banner=await saveBanner(data.bannerData,id);const gd=await load('games.json'),now=new Date().toISOString();gd.games.push({id,...fields,banner:banner||DEFAULT_BANNER,paused:false,createdAt:now,updatedAt:now});await save('games.json',gd);return send(res,200,{ok:true,id});
  }
  const gameMatch=url.pathname.match(/^\/api\/admin\/games\/([^/]+)$/);if(gameMatch&&req.method==='PUT'){const data=await body(req),gd=await load('games.json'),game=gd.games.find(x=>x.id===gameMatch[1]);if(!game)return fail(res,404,'游戏不存在');Object.assign(game,cleanGameInput(data,game));const banner=await saveBanner(data.bannerData,game.id);if(banner)game.banner=banner;game.updatedAt=new Date().toISOString();await save('games.json',gd);return send(res,200,{ok:true});}
  const pauseMatch=url.pathname.match(/^\/api\/admin\/games\/([^/]+)\/pause$/);if(pauseMatch&&req.method==='POST'){const gd=await load('games.json'),game=gd.games.find(x=>x.id===pauseMatch[1]);if(!game)return fail(res,404,'游戏不存在');game.paused=!game.paused;game.updatedAt=new Date().toISOString();await save('games.json',gd);return send(res,200,{ok:true,paused:game.paused});}
  if(gameMatch&&req.method==='DELETE'){const gd=await load('games.json'),game=gd.games.find(x=>x.id===gameMatch[1]);if(!game)return fail(res,404,'游戏不存在');gd.games=gd.games.filter(x=>x.id!==game.id);await save('games.json',gd);return send(res,200,{ok:true});}
  if(req.method==='POST'&&url.pathname==='/api/admin/logout'){adminSessions.delete(cookies(req).mud_admin);clearCookie(res,'mud_admin');return send(res,200,{ok:true});}
  return fail(res,404,'接口不存在');
}

async function persistSession(s){const db=await load('accounts.json'),account=db.accounts.find(x=>x.id===s.accountId);if(!account)throw new Error('账号不存在');migrateAccount(account);const entry=account.games[s.gameId]||{totalSeconds:0};entry.state=structuredClone(s.draft);entry.totalSeconds=(entry.totalSeconds||0)+s.activeSeconds;entry.lastPlayedAt=new Date().toISOString();account.games[s.gameId]=entry;s.activeSeconds=0;account.lastPlayedAt=entry.lastPlayedAt;await save('accounts.json',db);}
function chatEndpoint(baseUrl){const u=baseUrl.replace(/\/$/,'');return /\/chat\/completions$/i.test(u)?u:`${u}/chat/completions`;}
function relevantWorld(game,state,input){if(!game.engine?.world?.geographyRegions)return game.background;const regions=game.engine.world.geographyRegions,recent=(state.history||[]).slice(-2).map(x=>x.narrative).join(' '),context=`${state.location} ${input} ${recent}`,matched=regions.filter(r=>r.keywords.some(k=>context.includes(k)));return (matched.length?matched.slice(0,2):regions.filter(x=>x.id==='county')).map(x=>x.text).join('\n');}
function buildAiPrompt(state,input,game){const rules=[...defaultRules(),game.rules].join('\n');const current={playerName:state.playerName,character:state.character,turn:state.turn,chapter:state.chapter,location:state.location,time:state.time,hpStatus:state.hpStatus,resources:state.resources,inventory:state.inventory,relations:state.relations,flags:state.flags};let npcContext=game.npcs||'无预设主要NPC，由剧情按需生成。';if(game.engine?.heroines){const introduced=new Set(state.introducedHeroines||[]),known=game.engine.heroines.filter(h=>introduced.has(h.name)).map(h=>({...h,relation:state.relations[h.name]||0})),pending=game.engine.heroines.filter(h=>!introduced.has(h.name)).map(h=>({name:h.name,earliestTurn:h.earliestTurn}));npcContext=JSON.stringify({已登场人物:known,尚未登场人物:pending});}return `你是《${game.name}》MUD游戏的叙事引擎。\n\n【游戏简介】\n${introOf(game)}\n\n【默认主角设定】\n${game.protagonist}\n\n【玩家已自定义的主角元素】\n${JSON.stringify(state.character||{})}\n未自定义的主角属性沿用默认设定；默认设定没有说明时才由你合理生成，并保持前后一致。\n\n【当前剧情可能涉及的背景资料】\n${relevantWorld(game,state,input)}\n\n【主要NPC设定】\n${npcContext}\n\n【规则】\n${rules}\n\n【当前人物与道具状态】\n${JSON.stringify(current)}\n\n【长期剧情摘要】\n${state.longTermSummary}\n\n【最近5回合原文】\n${JSON.stringify((state.history||[]).slice(-5))}\n\n【玩家本轮行动】\n${input}\n\n现在进入第${state.turn+1}回合。除非规则明确指定上帝视角，否则全程使用第二人称的主角有限视角。不得直接透露主角尚未探索、询问、观察或感知到的人名、身份、动机、幕后事件和秘密；陌生人先按可见特征称呼。普通回合100至200个汉字，重大剧情200至500个汉字。只返回合法JSON，narrative必须是第一个字段：{"narrative":"第二人称剧情","options":["选项1","选项2","选项3","选项4"],"longTermSummary":"300至800字摘要","patch":{"chapter":"可选","location":"可选","time":"可选","hpStatus":"可选","resources":{},"relations":{},"inventory":[],"flags":{},"introducedHeroines":[]}}。不变化的patch字段不要输出。`;}
function partialNarrative(raw){const match=/"narrative"\s*:\s*"/.exec(raw);if(!match)return '';const source=raw.slice(match.index+match[0].length);let out='';for(let i=0;i<source.length;i++){const ch=source[i];if(ch==='"')break;if(ch!=='\\'){out+=ch;continue;}if(i+1>=source.length)break;const e=source[++i];if(e==='u'){const hex=source.slice(i+1,i+5);if(!/^[0-9a-fA-F]{4}$/.test(hex))break;out+=String.fromCharCode(parseInt(hex,16));i+=4;}else out+=({n:'\n',r:'\r',t:'\t',b:'\b',f:'\f','"':'"','\\':'\\','/':'/'})[e]??e;}return out;}
function streamContent(event){const c=event?.choices?.[0]?.delta?.content??event?.choices?.[0]?.message?.content??'';return typeof c==='string'?c:Array.isArray(c)?c.map(x=>x?.text||x?.content||'').join(''):'';}
async function readProviderStream(response,onNarrative){if(!response.body)return '';const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',raw='',emitted=0;const processLine=line=>{const t=line.trim();if(!t.startsWith('data:'))return;const data=t.slice(5).trim();if(!data||data==='[DONE]')return;try{raw+=streamContent(JSON.parse(data));const visible=partialNarrative(raw);if(visible.length>emitted){onNarrative(visible.slice(emitted));emitted=visible.length;}}catch{}};while(true){const{value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split(/\r?\n/);buffer=lines.pop()||'';for(const line of lines)processLine(line);}if(buffer)processLine(buffer);return raw;}
async function runAiTurn(state,input,game,onNarrative=()=>{}){state=normalizeState(state,game);const md=await load('models.json'),provider=md.models.find(x=>x.active);if(!provider)throw Object.assign(new Error('尚未配置可用的 AI 模型，请联系管理员'),{public:true});const prompt=buildAiPrompt(state,input,game),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),90000);let response,raw='',emitted=0;const emit=t=>{if(t){emitted+=t.length;onNarrative(t);}};const requestBody=stream=>JSON.stringify({model:provider.model,stream,messages:[{role:'system',content:'你是严谨、连续的中文MUD游戏引擎。必须输出合法JSON，不使用Markdown；narrative必须是第一个字段。'},{role:'user',content:prompt}]});try{response=await fetch(chatEndpoint(provider.baseUrl),{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json',Authorization:`Bearer ${decrypt(provider.apiKey)}`},body:requestBody(true)});if(!response.ok&&[400,404,415,422].includes(response.status)){await response.text();response=await fetch(chatEndpoint(provider.baseUrl),{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json',Authorization:`Bearer ${decrypt(provider.apiKey)}`},body:requestBody(false)});}if(!response.ok){console.error('AI provider error',response.status,(await response.text()).slice(0,500));throw Object.assign(new Error(`AI 接口返回 ${response.status}`),{public:true});}if((response.headers.get('content-type')||'').includes('text/event-stream'))raw=await readProviderStream(response,emit);else{const envelope=await response.json();raw=envelope.choices?.[0]?.message?.content||'';}}finally{clearTimeout(timer);}if(!raw)throw Object.assign(new Error('AI 未返回有效剧情'),{public:true});let result;try{result=JSON.parse(raw.replace(/^```json\s*|\s*```$/g,''));}catch{throw Object.assign(new Error('AI 返回格式无法解析，请重试'),{public:true});}if(typeof result.narrative!=='string'||!Array.isArray(result.options)||result.options.length!==4)throw Object.assign(new Error('AI 返回的剧情结构不完整，请重试'),{public:true});if(emitted<result.narrative.length)emit(result.narrative.slice(emitted));result.narrative=result.narrative.slice(0,3000);result.options=result.options.map(x=>String(x).slice(0,160));result.longTermSummary=String(result.longTermSummary||state.longTermSummary).slice(0,2400);return result;}

async function serveStatic(req,res,url){let pathname=decodeURIComponent(url.pathname);if(pathname==='/')pathname='/index.html';if(pathname==='/admin')pathname='/admin.html';if(pathname.startsWith('/uploads/')){const name=path.basename(pathname),file=path.join(BANNER_DIR,name);try{const data=await readFile(file);res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'public, max-age=86400','X-Content-Type-Options':'nosniff'});return res.end(data);}catch{return fail(res,404,'图片不存在');}}const allowed=new Set(['/index.html','/style.css','/hub.css','/stream.css','/app.js','/admin.html','/admin.js','/pnlsbanner.png','/gomudbanner.png','/default-banner.svg']);if(!allowed.has(pathname))return fail(res,404,'页面不存在');const file=path.join(ROOT,pathname.slice(1));try{const data=await readFile(file);res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':pathname.match(/\.(png|jpg|webp|svg)$/)?'public, max-age=3600':'no-cache','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'"});res.end(data);}catch{fail(res,404,'文件不存在');}}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);try{if(url.pathname.startsWith('/api/'))await routeApi(req,res,url);else await serveStatic(req,res,url);}catch(err){console.error(err);fail(res,err.public?400:500,err.public?err.message:'服务器暂时出了问题，请稍后再试');}});
server.listen(PORT,'0.0.0.0',()=>console.log(`来玩泥巴已启动：http://0.0.0.0:${PORT}`));
